### ISSUE TITLE
Deep (nested) component support

### ISSUE THREAD

**Issue by nathancahill** [wyze/preact-to-json#1]
Hey Neil, I saw your package, but wrote my own based off [developit/preact-render-to-string](https://github.com/developit/preact-render-to-string). It's here: [nathancahill/preact-render-to-json](https://github.com/nathancahill/preact-render-to-json). This supports nested components, and the rest of the Preact API. Want to give it a mention in your "shallow" disclaimer?

**Comment by wyze** [comment]
Done,. Thank you for bringing this to my attention, Nathan.
